# Use this to quickly spin up a local database for development
#
# Usage:
#   docker-compose up -d
#   docker-compose down
#
version: '3.8'
services:
  db:
    image: mariadb:10.6
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_ROOT_PASSWORD: 'rootpassword'
      MARIADB_DATABASE: 'siakad'
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
